services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/annapel_db?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=4818139
      - SPRING_CORS_ORIGINS=http://vps-4929384-x.dattaweb.com
      - JWT_SECRET=annapelSecretKey123456789012345678901234567890
    depends_on:
      db:
          condition: service_healthy

  db:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 4818139
      MYSQL_PASSWORD: 4818139
      MYSQL_DATABASE: annapel_db
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend